package docs

import (
	e "github.com/willoma/gomplements"

	c "bulma-gomponents.docs/components"
	b "github.com/willoma/bulma-gomponents"
)

var pagination = c.NewPage(
	"Pagination", "Pagination", "/pagination",
	"",
	b.Content(
		e.P("The ", e.Code("b.Pagination"), " constructor creates a pagination."),
		c.Modifiers(
			c.Row("b.Centered", `Center the pagination list ("Previous" button on the left side, "Next" on the right side)`),
			c.Row("b.Right", `Align the pagination list to the right ("Previous" and "Next" buttons on the left side)`),
			c.Row("b.Rounded", "Have rounded pagination buttons"),
			c.Row("b.Small", "Set size to small"),
			c.Row("b.Medium", "Set size to medium"),
			c.Row("b.Large", "Set size to large"),
		),
		c.Children(
			c.Row("b.OnList(...any)", "Apply children to the ", e.Code(`<ul class="pagination-list">`), " element"),
			c.Row("b.PaginationLink(...any)", "Add button-looking link to the ", e.Code(`<ul class="pagination-list">`), " element"),
			c.Row("b.PaginationEllipsis(...any)", "Add ellipsis to the ", e.Code(`<ul class="pagination-list">`), " element"),
			c.RowDefault("Apply child to the ", e.Code(`<nav class="pagination">`), " element"),
		),
		e.P("The ", e.Code("b.PaginationPrevious"), " and ", e.Code("b.PaginationNext"), " constructors create button-looking links."),
		e.P("The ", e.Code("b.PaginationLink"), " and ", e.Code("b.PaginationAHref"), " constructors create button-looking links for the pagination list section."),
		c.Modifiers(
			c.Row("b.Current", "Mark this link as being the current page"),
			c.Row("b.Disabled", "Mark this link as inactive"),
		),
		e.P("The ", e.Code("b.PaginationEllipsis"), " constructor creates an ellipsis for the pagination list section."),
	),
).Section(
	"Bulma examples", "https://bulma.io/documentation/components/pagination/",
	c.HorizontalExample(
		`b.Pagination(
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
	b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
	b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
)`,
		b.Pagination(
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
			b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
			b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
		),
	),
	c.HorizontalExample(
		`b.Pagination(
	b.PaginationPrevious(b.Disabled, "Previous", e.TitleAttr("This is the first page")),
	b.PaginationNext("Next page"),
	b.PaginationLink(e.AriaLabel("Page 1"), b.Current, "1"),
	b.PaginationLink(e.AriaLabel("Goto page 2"), "2"),
	b.PaginationLink(e.AriaLabel("Goto page 3"), "3"),
)`,
		b.Pagination(
			b.PaginationPrevious(b.Disabled, "Previous", e.TitleAttr("This is the first page")),
			b.PaginationNext("Next page"),
			b.PaginationLink(e.AriaLabel("Page 1"), b.Current, "1"),
			b.PaginationLink(e.AriaLabel("Goto page 2"), "2"),
			b.PaginationLink(e.AriaLabel("Goto page 3"), "3"),
		),
	),
	c.HorizontalExample(
		`b.Pagination(
	b.Centered,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
	b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
	b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Centered,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
			b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
			b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
		),
	),
	c.HorizontalExample(
		`b.Pagination(
	b.Right,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
	b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
	b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Right,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
			b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
			b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
		),
	),
).Subsection(
	"Styles",
	"https://bulma.io/documentation/components/pagination/#styles",
	c.HorizontalExample(
		`b.Pagination(
	b.Rounded,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
	b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
	b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Rounded,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
			b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
			b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
		),
	),
).Subsection(
	"Sizes",
	"https://bulma.io/documentation/components/pagination/#sizes",
	c.HorizontalExample(
		`b.Pagination(
	b.Small,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
	b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
	b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Small,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
			b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
			b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
		),
	),
	c.HorizontalExample(
		`b.Pagination(
	b.Medium,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
	b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
	b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Medium,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
			b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
			b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
		),
	),
	c.HorizontalExample(
		`b.Pagination(
	b.Large,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
	b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
	b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Large,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(e.AriaLabel("Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 45"), "45"),
			b.PaginationLink(e.AriaLabel("Goto page 46"), b.Current, "46"),
			b.PaginationLink(e.AriaLabel("Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(e.AriaLabel("Goto page 86"), "86"),
		),
	),
)
