package docs

import (
	e "github.com/willoma/gomplements"

	c "bulma-gomponents.docs/components"
	b "github.com/willoma/bulma-gomponents"
)

var classes = c.NewPage(
	"Classes and styles", "CSS Classes and styles", "/classes",
	"",

	b.Message(
		b.Danger,
		"Please note the ", e.Em("Gomplements"), " classes and styles do not work on traditional ", e.Code("gomponents.Node"), " elements, only on ", e.Code("e.Element"), ".",
	),
).Section(
	"Classes", "",
	b.Content(
		e.P(e.Em("Gomplements"), " provides a ", e.Code("Class"), " type, which applies the provided class to the element. You may use multiple classes as different arguments to an element builder, they are combined when rendering."),
	),
	c.Example(
		`e.Div(
	e.Class("myMenu"),
	"Here is my menu",
)`,
		e.Div(
			e.Class("myMenu"),
			"Here is my menu",
		),
	),
).Section(
	"Styles", "",
	b.Content(
		e.P("In order to apply CSS styles directly to an element, you may use the ", e.Code("e.Styles"), " map type."),
	),
	c.Example(
		`e.Div(
	e.Styles{
		"width":  "88px",
		"height": "44px",
		"border": "1px dashed red",
	},
	"Hello world",
)`,
		e.Div(
			e.Styles{
				"width":      "200px",
				"height":     "50px",
				"text-align": "center",
				"border":     "1px dashed red",
			},
			"Hello world",
		),
	),
).Section(
	"Responsiveness", "https://bulma.io/documentation/start/responsiveness/",
	b.Content(
		e.P("Responsive variants may be generated by using one of the following methods on ", e.Code("b.ResponsiveClass"), " or ", e.Code("b.ResponsiveClasses"), " values:"),
		c.Table(
			b.HeadRow("Method", "Action"),
			c.Row(".Mobile()", "Apply on mobile (up to ", e.Strong("768px"), ")"),
			c.Row(".TabletOnly()", "Apply on tablet (between ", e.Strong("769px"), " and ", e.Strong("1023px"), ")"),
			c.Row(".Tablet()", "Apply on tablet and larger"),
			c.Row(".Touch()", "Apply on mobile and tablet"),
			c.Row(".DesktopOnly()", "Apply on desktop (between ", e.Strong("1024px"), " and ", e.Strong("1215px"), ")"),
			c.Row(".Desktop()", "Apply on desktop and larger"),
			c.Row(".WidescreenOnly()", "Apply on widescreen (between ", e.Strong("1216px"), " and ", e.Strong("1407px"), ")"),
			c.Row(".Widescreen()", "Apply on widescreen and full HD"),
			c.Row(".FullHD()", "Apply on full HD (", e.Strong("1408px"), " and above)"),
		),
		e.P("On ", e.Code("b.ResponsiveClasses"), " values, the responsive variant is applied only on classes provided in the ", e.Code("Responsive"), " attribute."),
	),
	c.Example(
		`e.Div(
	b.FontSize7,
	b.FontSize6.Tablet(),
	b.FontSize5.Desktop(),
	b.FontSize4.Widescreen(),
	b.FontSize3.FullHD(),
	"Hello, my size changes according to your screen",
)`,
		e.Div(
			b.FontSize7,
			b.FontSize6.Tablet(),
			b.FontSize5.Desktop(),
			b.FontSize4.Widescreen(),
			b.FontSize3.FullHD(),
			"Hello, my size changes according to your screen",
		),
	),
)
