package docs

import (
	"github.com/maragudk/gomponents/html"

	b "github.com/willoma/bulma-gomponents"
	c "github.com/willoma/bulma-gomponents/docs/components"
)

var pagination = c.NewPage(
	"Pagination", "Pagination", "/pagination",
	"https://bulma.io/documentation/components/pagination/",
	c.HorizontalExample(
		`b.Pagination(
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
	b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
	b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
)`,
		b.Pagination(
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
			b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
			b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
		),
	),
	c.HorizontalExample(
		`b.Pagination(
	b.PaginationPrevious(b.Disabled, "Previous", html.TitleAttr("This is the first page")),
	b.PaginationNext("Next page"),
	b.PaginationLink(html.Aria("label", "Page 1"), b.Current, "1"),
	b.PaginationLink(html.Aria("label", "Goto page 2"), "2"),
	b.PaginationLink(html.Aria("label", "Goto page 3"), "3"),
)`,
		b.Pagination(
			b.PaginationPrevious(b.Disabled, "Previous", html.TitleAttr("This is the first page")),
			b.PaginationNext("Next page"),
			b.PaginationLink(html.Aria("label", "Page 1"), b.Current, "1"),
			b.PaginationLink(html.Aria("label", "Goto page 2"), "2"),
			b.PaginationLink(html.Aria("label", "Goto page 3"), "3"),
		),
	),
	c.HorizontalExample(
		`b.Pagination(
	b.Centered,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
	b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
	b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Centered,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
			b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
			b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
		),
	),
	c.HorizontalExample(
		`b.Pagination(
	b.Right,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
	b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
	b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Right,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
			b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
			b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
		),
	),
).Section(
	"Styles",
	"https://bulma.io/documentation/components/pagination/#styles",
	c.HorizontalExample(
		`b.Pagination(
	b.Rounded,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
	b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
	b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Rounded,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
			b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
			b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
		),
	),
).Section(
	"Sizes",
	"https://bulma.io/documentation/components/pagination/#sizes",
	c.HorizontalExample(
		`b.Pagination(
	b.Small,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
	b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
	b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Small,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
			b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
			b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
		),
	),
	c.HorizontalExample(
		`b.Pagination(
	b.Medium,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
	b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
	b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Medium,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
			b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
			b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
		),
	),
	c.HorizontalExample(
		`b.Pagination(
	b.Large,
	b.PaginationPrevious("Previous"),
	b.PaginationNext("Next page"),
	b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
	b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
	b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
	b.PaginationEllipsis(),
	b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
)`,
		b.Pagination(
			b.Large,
			b.PaginationPrevious("Previous"),
			b.PaginationNext("Next page"),
			b.PaginationLink(html.Aria("label", "Goto page 1"), "1"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 45"), "45"),
			b.PaginationLink(html.Aria("label", "Goto page 46"), b.Current, "46"),
			b.PaginationLink(html.Aria("label", "Goto page 47"), "47"),
			b.PaginationEllipsis(),
			b.PaginationLink(html.Aria("label", "Goto page 86"), "86"),
		),
	),
)
