package docs

import (
	b "github.com/willoma/bulma-gomponents"
	c "github.com/willoma/bulma-gomponents/docs/components"
	"github.com/willoma/bulma-gomponents/el"
)

var classes = c.NewPage(
	"Classes and styles", "CSS Classes and styles", "/classes",
	"",

	b.Message(
		b.Danger,
		"Please note the ", el.Em("Bulma-Gomponents"), " classes and styles do not work on traditional ", el.Code("gomponents.Node"), " elements, only on ", el.Code("b.Element"), ".",
	),
).Section(
	"Classes", "",
	b.Content(
		el.P(el.Em("Bulma-Gomponents"), " provides a ", el.Code("Class"), " type, which applies the provided class to the element. You may use multiple classes as different arguments to an element builder, they are combined when rendering."),
	),
	c.Example(
		`el.Div(
	b.Class("myMenu"),
	"Here is my menu",
)`,
		el.Div(
			b.Class("myMenu"),
			"Here is my menu",
		),
	),
).Section(
	"Styles", "",
	b.Content(
		el.P("In order to apply CSS styles directly to an element, you may use the ", el.Code("b.Style"), " function, which takes a serie of property/value tuples."),
	),
	c.Example(
		`el.Div(
	b.Style(
		"width", "88px",
		"height", "44px",
		"border", "1px dashed red",
	),
	"Hello world",
)`,
		el.Div(
			b.Style(
				"width", "200px",
				"height", "50px",
				"text-align", "center",
				"border", "1px dashed red",
			),
			"Hello world",
		),
	),
).Section(
	"Responsiveness", "https://bulma.io/documentation/start/responsiveness/",
	b.Content(
		el.P("Responsive variants may be generated by using one of the following functions on ", el.Code("b.Class"), " or ", el.Code("b.MultiClass"), " values:"),
		el.Ul(
			el.Li(el.Code(".Mobile()"), ": mobile screens"),
			el.Li(el.Code(".Tablet()"), ": tablet and larger screens"),
			el.Li(el.Code(".TabletOnly()"), ": tablet screens"),
			el.Li(el.Code(".Touch()"), ": mobile and tablet screens"),
			el.Li(el.Code(".Desktop()"), ": desktop and larger screens"),
			el.Li(el.Code(".DesktopOnly()"), ": desktop screens"),
			el.Li(el.Code(".Widescreen()"), ": widescreen and larger screens"),
			el.Li(el.Code(".WidescreenOnly()"), ": widescreen screens"),
			el.Li(el.Code(".FullHD()"), ": full hd screens"),
		),
		el.P("On ", el.Code("b.MultiClass"), " values, the responsive variant is applied only on classes provided in the ", el.Code("Responsive"), " attribute. Obviously, even if ", el.Em("Bulma-Gomponents"), " can apply these variants on all classes, it is useful only on those supported by ", el.Em("Bulma"), "."),
	),
	c.Example(
		`el.Div(
	b.FontSize7,
	b.FontSize6.Tablet(),
	b.FontSize5.Desktop(),
	b.FontSize4.Widescreen(),
	b.FontSize3.FullHD(),
	"Hello, my size changes according to your screen",
)`,
		el.Div(
			b.FontSize7,
			b.FontSize6.Tablet(),
			b.FontSize5.Desktop(),
			b.FontSize4.Widescreen(),
			b.FontSize3.FullHD(),
			"Hello, my size changes according to your screen",
		),
	),
)
