package docs

import (
	b "github.com/willoma/bulma-gomponents"
	c "github.com/willoma/bulma-gomponents/docs/components"
	"github.com/willoma/bulma-gomponents/el"
)

var intro = c.NewPage(
	"Intro", "Bulma-Components", "//index",
	"https://bulma.io/documentation/",

	b.Content(
		"This ", el.Em("Go"), " library makes it easier to use the Bulma CSS framework with the Gomponents library.",
		el.H2("Examples"),
		el.P("The examples in this documentation refer to examples in the ", b.AHref("https://bulma.io/documentation/", "official Bulma documentation"), "."),
		"All examples consider that Bulma-Gomponents has been imported with:",
		el.Pre(`import b "github.com/willoma/bulma-gomponents"`),
		el.H2("Document root"),
		el.P("In order to generate a document root, use ", el.Code("b.HTML(...any)"), ". The allowed options are:"),
		b.DList(
			el.Code("b.CSSPath(string)"),
			[]any{"path to the CSS file, to provide in the ", el.Code(`<link rel="stylesheet">`), " node (if it is not defined, the default CDN is used)"},
			el.Code("b.Language(string)"),
			"define the document language",
			el.Code("b.HTitle(string)"),
			"define the document title",
			el.Code("b.Description(string)"),
			"define the document description",
			el.Code("b.Head(...gomponents.Node)"),
			[]any{"add one or multiple children to the ", el.Code("<head>")},
			"any other value",
			[]any{"add the node to the ", el.Code("<body>")},
		),
		el.H2("Classes and styles"),
		el.P("To apply a custom class to an element, use ", el.Code("b.Class(string)"), ". Bulma-specific classes are defined in this library, see the other docs pages. You may use it multiple times, classes are combined."),
		el.P("To apply a CSS style to an element, use ", el.Code("b.Style(property, value string)"), ". You may use it multiple times, styles are combined."),
		el.P("Please note these two functions only work on element generated by Bulma-Gomponents, not on traditional ", el.Code("gomponents.Node"), " elements."),
		el.H2("Responsive values"),
		el.P("In order to generate a responsive value for a class, use the corresponding function, from ", el.Code("(value).Mobile"), " to ", el.Code("(value).FullHD"), "."),
		el.P("For instance, to set the font size to 2 on tablet upwards, use ", el.Code("b.FontSize2.Tablet()"), "."),
	),
)
